# Generated by Django 5.2.8 on 2026-02-11 11:26

from django.db import migrations, models
import uuid


def populate_transaction_numbers(apps, schema_editor):
    """Populate transaction numbers for existing payment records"""
    Payment = apps.get_model('billing', 'Payment')
    for payment in Payment.objects.filter(transaction_number__isnull=True):
        payment.transaction_number = f"TXN-{uuid.uuid4().hex[:12].upper()}"
        payment.save(update_fields=['transaction_number'])
    # Also handle empty strings
    for payment in Payment.objects.filter(transaction_number=''):
        payment.transaction_number = f"TXN-{uuid.uuid4().hex[:12].upper()}"
        payment.save(update_fields=['transaction_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feecategory',
            options={'ordering': ['display_order', 'category_name'], 'verbose_name': 'Fee Category', 'verbose_name_plural': 'Fee Categories'},
        ),
        migrations.AddField(
            model_name='feecategory',
            name='category_name_arabic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fee Category Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='description_arabic',
            field=models.TextField(blank=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_printed',
            field=models.BooleanField(default=False, verbose_name='Receipt Printed'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Receipt Printed At'),
        ),
        # First add the field without unique constraint
        migrations.AddField(
            model_name='payment',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transaction Number', null=True),
        ),
        # Populate existing records
        migrations.RunPython(populate_transaction_numbers, migrations.RunPython.noop),
        # Now add the unique constraint
        migrations.AlterField(
            model_name='payment',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Transaction Number'),
        ),
    ]
