# Generated by Django 5.2.8 on 2026-02-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Admission Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Emergency Contact Relation'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Father Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Father Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name_arabic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Father Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Father National ID / Iqama'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Father Occupation'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Father Phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='file_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Student File Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_arabic',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grade/Class'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_level_arabic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grade/Class (Arabic)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_arabic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mother Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name_arabic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mother Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mother Phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Student National ID / Iqama'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Internal Notes'),
        ),
    ]
