# Generated by Django 5.2.8 on 2026-02-11 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('student', 'Student Report'), ('financial', 'Financial Report'), ('attendance', 'Attendance Report'), ('enrollment', 'Enrollment Report'), ('fee_collection', 'Fee Collection Report'), ('outstanding', 'Outstanding Fees Report'), ('performance', 'Academic Performance Report'), ('class_wise', 'Class-wise Report')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('email_recipients', models.TextField(help_text='Comma-separated email addresses')),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('student', 'Student Report'), ('financial', 'Financial Report'), ('attendance', 'Attendance Report'), ('enrollment', 'Enrollment Report'), ('fee_collection', 'Fee Collection Report'), ('outstanding', 'Outstanding Fees Report'), ('performance', 'Academic Performance Report'), ('class_wise', 'Class-wise Report')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('total_records', models.IntegerField(default=0)),
                ('summary_data', models.JSONField(default=dict)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('excel_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['-generated_at'], name='reports_sav_generat_da1ba8_idx'), models.Index(fields=['report_type'], name='reports_sav_report__4cdcd0_idx')],
            },
        ),
    ]
