# Generated by Django 5.2.8 on 2026-02-11 09:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_arabic', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('organization_code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Saudi Arabia', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/logos/')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_name_arabic', models.CharField(blank=True, max_length=200, null=True)),
                ('school_code', models.CharField(max_length=50, unique=True)),
                ('school_type', models.CharField(choices=[('boys', 'Boys School'), ('girls', 'Girls School'), ('mixed', 'Co-education')], default='mixed', max_length=20)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('full_day', 'Full Day')], default='morning', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('accreditation_body', models.CharField(blank=True, max_length=200, null=True)),
                ('accreditation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('establishment_date', models.DateField(blank=True, null=True)),
                ('principal_name', models.CharField(max_length=200)),
                ('principal_email', models.EmailField(max_length=254)),
                ('principal_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('total_capacity', models.PositiveIntegerField(default=0, help_text='Maximum student capacity')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.organization')),
            ],
            options={
                'ordering': ['organization', 'school_name'],
                'unique_together': {('organization', 'school_code')},
            },
        ),
        migrations.CreateModel(
            name='AcademicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('academic_year_start', models.DateField()),
                ('academic_year_end', models.DateField()),
                ('number_of_terms', models.PositiveIntegerField(default=2, help_text='Number of terms/semesters per academic year', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('working_days', models.CharField(default='sunday,monday,tuesday,wednesday,thursday', help_text='Comma-separated working days', max_length=50)),
                ('class_start_time', models.TimeField(default='07:30:00')),
                ('class_end_time', models.TimeField(default='14:00:00')),
                ('class_duration', models.PositiveIntegerField(default=45, help_text='Class duration in minutes')),
                ('break_duration', models.PositiveIntegerField(default=10, help_text='Break duration in minutes')),
                ('grading_system', models.CharField(choices=[('percentage', 'Percentage (0-100)'), ('gpa_4', 'GPA 4.0 Scale'), ('gpa_5', 'GPA 5.0 Scale'), ('letter', 'Letter Grades (A-F)'), ('custom', 'Custom System')], default='percentage', max_length=20)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('minimum_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum attendance required for promotion', max_digits=5)),
                ('auto_promotion_enabled', models.BooleanField(default=False)),
                ('promotion_criteria', models.TextField(blank=True, help_text='Custom promotion criteria/rules', null=True)),
                ('late_arrival_grace_period', models.PositiveIntegerField(default=15, help_text='Grace period in minutes before marking late')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_config', to='schools.school')),
            ],
            options={
                'verbose_name': 'Academic Configuration',
                'verbose_name_plural': 'Academic Configurations',
            },
        ),
        migrations.CreateModel(
            name='SchoolBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#1e40af', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#059669', help_text='Hex color code', max_length=7)),
                ('accent_color', models.CharField(default='#dc2626', help_text='Hex color code', max_length=7)),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='schools/branding/headers/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='schools/branding/footers/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='schools/branding/favicons/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='schools/branding/backgrounds/')),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('tagline_arabic', models.CharField(blank=True, max_length=200, null=True)),
                ('vision_statement', models.TextField(blank=True, null=True)),
                ('mission_statement', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('report_header_text', models.TextField(blank=True, null=True)),
                ('report_footer_text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Branding',
                'verbose_name_plural': 'School Branding',
            },
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('academic_director', 'Academic Director'), ('admin_officer', 'Administrative Officer'), ('registrar', 'Registrar'), ('coordinator', 'Coordinator')], max_length=30)),
                ('can_manage_students', models.BooleanField(default=False)),
                ('can_manage_teachers', models.BooleanField(default=False)),
                ('can_manage_curriculum', models.BooleanField(default=False)),
                ('can_manage_fees', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_manage_timetable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_admin_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school', 'role'],
                'unique_together': {('school', 'user', 'role')},
            },
        ),
    ]
