# Generated by Django 5.2.8 on 2026-02-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cr_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='CR Number (Commercial Registration)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='school',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Number'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vat_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Registration Number'),
        ),
    ]
