# Generated by Django 5.2.8 on 2026-02-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Elementary School', max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g., ELEM', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2025-2026', max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one year can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Year',
                'verbose_name_plural': 'School Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VATConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=15.0, help_text='VAT percentage (e.g., 15 for 15%)', max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank if still active', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Notes about this VAT configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VAT Configuration',
                'verbose_name_plural': 'VAT Configurations',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Grade 1, Grade 2', max_length=50)),
                ('code', models.CharField(help_text='e.g., G1, G2', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='settings_app.program')),
            ],
            options={
                'verbose_name': 'Grade/Class',
                'verbose_name_plural': 'Grades/Classes',
                'ordering': ['program', 'order'],
                'unique_together': {('program', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Regular Tuition - Grade 1', max_length=200)),
                ('fee_type', models.CharField(choices=[('Tuition', 'Tuition Fee'), ('Transport', 'Transport Fee'), ('Books', 'Books & Materials'), ('Uniform', 'Uniform'), ('Activities', 'Extracurricular Activities'), ('Registration', 'Registration Fee'), ('Examination', 'Examination Fee'), ('Other', 'Other Fees')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in SAR', max_digits=10)),
                ('payment_schedule', models.CharField(choices=[('Annual', 'Annual (Once per year)'), ('Semester', 'Semester (Twice per year)'), ('Quarterly', 'Quarterly (4 times per year)'), ('Monthly', 'Monthly'), ('One-time', 'One-time Payment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='settings_app.grade')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='settings_app.program')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['program', 'grade', 'fee_type'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., A, B, C', max_length=10)),
                ('capacity', models.IntegerField(default=30, help_text='Maximum number of students')),
                ('current_strength', models.IntegerField(default=0, help_text='Current number of students')),
                ('class_teacher', models.CharField(blank=True, help_text='Class teacher name', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='settings_app.grade')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['grade', 'name'],
                'unique_together': {('grade', 'name')},
            },
        ),
    ]
